version: "3.8"
services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - gitea
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      tempnet:
        ipv4_address: 10.5.0.3
  gitea:
    image: gitea/gitea:1.20.4
    container_name: gitea
    restart: always
    volumes:
      - ./gitea/data:/data
      - ./gitea/logs:/app/gitea/logs
      - ./gitea/custom:/app/gitea/custom
      - /etc/timezone:/etc/timezone:ru
      - /etc/localtime:/etc/localtime:ru
    ports:
      - "3000:3000"
      - "22:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=test-domain-name
    networks:
      tempnet:
        ipv4_address: 10.5.0.4
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    container_name: elastic 
    networks:
      tempnet:
        ipv4_address: 10.5.0.5
  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elastic
    networks:
      tempnet:
        ipv4_address: 10.5.0.6
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://10.5.0.5:9200
    depends_on:
      - elastic
    networks:
      tempnet:
        ipv4_address: 10.5.0.7
networks:
  tempnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
